package com.person.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

import static com.person.AppConstants.DYNAMO_TABLE;
import static com.person.AppConstants.KEY_ID;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = DYNAMO_TABLE)
public class Person implements Serializable {

    @DynamoDBHashKey(attributeName = KEY_ID)
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String firstname;

    @DynamoDBAttribute
    private String lastname;

    @DynamoDBAttribute
    private String phonenumber;

    @DynamoDBAttribute
    private Address address;

}